# Nombre del workflow, aparecerá en la pestaña 'Actions' de tu repositorio
name: Despliegue de Angular a GitHub Pages

# Eventos que dispararán este workflow
on:
  push:
    # Se ejecutará cuando se haga un push a la rama 'main'
    branches: ["main"]
  pull_request:
    # Opcional: Se ejecutará cuando se abra o actualice un pull request a 'main'
    branches: ["main"]
  # Permite ejecutar este workflow manualmente desde la pestaña 'Actions'
  workflow_dispatch:

# Permisos necesarios para que el GITHUB_TOKEN pueda desplegar en Pages
permissions:
  contents: read   # Necesario para leer el código del repositorio
  pages: write     # Necesario para escribir en el repositorio de Pages
  id-token: write  # Necesario para la autenticación con OIDC (OpenID Connect)

# Esto asegura que solo una ejecución de despliegue se ejecute a la vez.
# Si hay un despliegue en progreso y se dispara otro, el anterior será cancelado.
concurrency:
  group: "pages"
  cancel-in-progress: true

# Definición de los trabajos (jobs) que se ejecutarán
jobs:
  # Job para construir la aplicación Angular
  build:
    runs-on: ubuntu-latest # El sistema operativo donde se ejecutará el job

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout del código
        uses: actions/checkout@v4

      # Paso 2: Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          # Usamos una versión específica de Node.js para la construcción.
          # Puedes cambiarla si tu proyecto requiere otra.
          node-version: 20.x
          # Caching de dependencias para acelerar futuras ejecuciones
          cache: 'npm'

      # Paso 3: Instalar las dependencias del proyecto
      - name: Instalar dependencias
        run: npm ci # 'npm ci' es más seguro y rápido para CI/CD que 'npm install'

      # Paso 4: Construir la aplicación Angular
      # Este comando ejecutará el script 'build' definido en tu package.json (normalmente 'ng build').
      # La opción '--base-href' es crucial para que Angular genere rutas correctas para GitHub Pages.
      # La salida por defecto de Angular es 'dist/<nombre-del-proyecto>', que para este repo es 'dist/poli-market-angular'.
      - name: Construir la aplicación Angular
        run: npm run build -- --base-href=/polimarket_angular/ --configuration=production

      # Paso 5: Listar contenido de la carpeta dist para depuración
      # Este paso nos ayudará a verificar si la construcción se realizó correctamente
      # y cuál es la ruta exacta de salida.
      - name: Listar contenido de dist
        run: ls -lR dist

      # Paso 6: Subir el artefacto de construcción para GitHub Pages
      # Este paso toma la carpeta de salida de tu build de Angular y la hace disponible para el job de despliegue.
      - name: Subir artefacto para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Ruta a la carpeta de salida de tu build de Angular.
          # Hemos ajustado la ruta a 'dist/poli-market-angular/browser' según la salida de 'ls -lR dist'.
          path: ./dist/poli-market-angular/browser

  # Job para desplegar la aplicación en GitHub Pages
  deploy:
    # Este job depende del job 'build'. Solo se ejecutará si 'build' es exitoso.
    needs: build
    runs-on: ubuntu-latest # El sistema operativo donde se ejecutará el job

    # Define el entorno de despliegue. Esto ayuda a organizar los despliegues en GitHub.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # La URL del sitio desplegado

    steps:
      # Paso 1: Desplegar el artefacto subido a GitHub Pages
      - name: Desplegar a GitHub Pages
        id: deployment # ID para referenciar los outputs de este paso
        uses: actions/deploy-pages@v4 # Acción oficial para desplegar en GitHub Pages
